package libs;

import org.aeonbits.owner.Config;

public interface ConfigProperties extends Config {
	long TIME_FOR_DFFAULT_WAIT();
	long TIME_FOR_EXPLICIT_WAIT_LOW();
	long TIME_FOR_EXPLICIT_WAIT_HIGHT();

	String OPERATOR_LOGIN_FOR_TEST();
	String OPERATOR_PASSWORD_FOR_TEST();

	String CS_OPERATOR_LOGIN();
	String CS_OPERATOR_PASSWORD();

	String base_url();
	String addUrl();
	String DATA_FILE();
	String DATA_FILE_PATH();
	String Oracle();
	String MySQL();
	String sqlServer();

	String MySQL_DB();
	String MySQL_DB_USER();
	String MySQL_DB_PASSWORD();

	String ORACLE_SQL_DB();
	String ORACLE_SQL_DB_USER();
	String ORACLE_SQL_DB_PASSWORD();

	String GET_SMS_CODE_FOR_AUTH();
	String GET_SMS_CODE_FOR_SELL();
	String GET_CURRENT_LZ_DRAW();
	String GET_MACCODE_FOR_MEGALOT_WIN_PAYMENT();
	String GET_TICKET_WIN_SUM();
	String DRAW_COUNT_IN_REGISTRATION_BET_STATUS();
	String DRAW_COUNT_IN_MULTY_REGISTRATION_BET_STATUS();
	String DRAW_COUNT_IN_CREATED_STATUS();
	String SCRIPT_FOR_CHANGING_DDRAW_STATUS_INTO_REGISTRATION_1();
	String SCRIPT_FOR_CHANGING_DDRAW_STATUS_INTO_REGISTRATION_2();
	String DRAW_ID_IN_REGISTRATION_BET_STATUS();
	String DRAW_ID_IN_MULTY_REGISTRATION_BET_STATUS();
	String DRAW_ID_IN_CREATED_STATUS();
	String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_1();
	String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_2();
    String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_3();
}
