package libs;

import org.aeonbits.owner.Config;

public interface ConfigProperties extends Config {
	long TIME_FOR_DFFAULT_WAIT();
	long TIME_FOR_EXPLICIT_WAIT_LOW();
	long TIME_FOR_EXPLICIT_WAIT_HIGHT();

	String OPERATOR_LOGIN_FOR_TEST();
	String OPERATOR_PASSWORD_FOR_TEST();

	String CS_OPERATOR_LOGIN();
	String CS_OPERATOR_PASSWORD();

	String base_url();
	String addUrl();
	String DATA_FILE();
	String DATA_FILE_PATH();
	String Oracle();
	String MySQL();
	String sqlServer();

	String MySQL_DB();
	String MySQL_DB_USER();
	String MySQL_DB_PASSWORD();

	String ORACLE_SQL_DB();
	String ORACLE_SQL_DB_USER();
	String ORACLE_SQL_DB_PASSWORD();

	String GET_SMS_CODE_FOR_AUTH();
	String GET_SMS_CODE_FOR_SELL();
	String GET_CURRENT_LZ_DRAW();
	String GET_MACCODE_FOR_MEGALOT_WIN_PAYMENT();
	String GET_TICKET_WIN_SUM();
	String DRAW_COUNT_IN_REGISTRATION_BET_STATUS();
	String DRAW_COUNT_IN_MULTY_REGISTRATION_BET_STATUS();
	String DRAW_COUNT_IN_CREATED_STATUS();
	String SCRIPT_FOR_CHANGING_DDRAW_STATUS_INTO_REGISTRATION_1();
	String SCRIPT_FOR_CHANGING_DDRAW_STATUS_INTO_REGISTRATION_2();
	String DRAW_ID_IN_REGISTRATION_BET_STATUS();
	String DRAW_ID_IN_MULTY_REGISTRATION_BET_STATUS();
	String DRAW_ID_IN_CREATED_STATUS();
	String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_1();
	String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_2();
    String SCRIPT_FOR_CREATION_DRAW_IN_CREATED_STATUS_3();
    String SCRIPT_DRAW_CODE();
    String DRAW_ID_OF_CREATED_DRAW();
    String CHANGE_DRAW_PARAMS_SCRIPT_1();
	String CHANGE_DRAW_PARAMS_SCRIPT_2();
	String CHANGE_DRAW_PARAMS_SCRIPT_3();
	String CHANGE_DRAW_PARAMS_SCRIPT_4();
	String CHANGE_DRAW_PARAMS_SCRIPT_5();
	String CHANGE_DRAW_PARAMS_SCRIPT_6();
	String CHANGE_DRAW_PARAMS_SCRIPT_7();
	String CHANGE_DRAW_PARAMS_SCRIPT_8();
	String CHANGE_DRAW_PARAMS_SCRIPT_9();
	String CHANGE_DRAW_PARAMS_SCRIPT_10();
	String CHANGE_DRAW_PARAMS_SCRIPT_11();
	String CHANGE_DRAW_PARAMS_SCRIPT_12();
	String SCRIPT_FOR_CHANGING_DRAW_STATUS_INTO_MULTY_REGISTRATION_1();
	String SCRIPT_FOR_CHANGING_DRAW_STATUS_INTO_MULTY_REGISTRATION_2();
	String REFORM_BLOB_SCRIPT_1();
	String REFORM_BLOB_SCRIPT_2();
}
